<!DOCTYPE html>
<html>
	<head>
		<title>Phalcon PHP Framework</title>
	</head>
	<body>
		<h1><?php echo $project->getNom() .' ['.$client->getIdentite() .']'; ?></h1>
		<h2>Details du projet</h2> 
		Description : <?php echo $project->getDescription(); ?>
		<br>
		Date Lancement : <?php echo $project->getDateLancement(); ?>
		<br>
		Date Fin Prévue : <?php echo $project->getDateFinPrevue(); ?>
		<br>
		<h2>Equipe</h2>
			
		<?php
			$tab = array();
			foreach ($useCases as $useCase) {					
				if (!isset($tab[$useCase->getUser()->getIdentite()]))
					$tab[$useCase->getUser()->getIdentite()] = 0;
				$tab[$useCase->getUser()->getIdentite()] += $useCase->getPoids();
			}
			foreach ($tab as $ta => $val) {
				echo $ta . '[' . $val . ']'."<br/>";
			}
		?>
	</body>
</html>