<!DOCTYPE html>
<html>
	<head>
		<title>Phalcon PHP Framework</title>
	</head>
	<body>
		<h1><?php echo $project->getNom() .' ['.$client->getIdentite() .']'; ?></h1>
		<h2>Details du projet</h2> 
		Description : <?php echo $project->getDescription(); ?>
		<br>
		Date Lancement : <?php echo $project->getDateLancement(); ?>
		<br>
		Date Fin Prévue : <?php echo $project->getDateFinPrevue(); ?>
		<br>
		<h2>Equipe</h2>
		<div id="detailProject">Chargement...</div>
		<?php
			echo '</br>';
			echo $q['btMasquer'];
			echo '<div id="ZoneMessages"></div>';
			echo $q["btFermer"];
			echo $script_foot;
		?>
	</body>
</html>